config/routes.rb
Catsanddogs::Application.routes.draw do
  resources :animal_areas

  root 'animal_areas#index'

  get 'areas' => 'animal_areas#areas', as: :areas

end

app/models/animal_area.rb
class AnimalArea < ActiveRecord::Base
  validates :forward_sorting_area, uniqueness: true, presence: true

  geocoded_by :address

  after_validation :geocode,
    :if => lambda{ |animal_area| animal_area.forward_sorting_area_changed? }

  def address
    "#{forward_sorting_area}, Toronto, Ontario, Canada"
  end

end

app/controllers/animal_areas_controller.rb
class AnimalAreasController < ApplicationController
  before_action :set_animal_area, only: [:show, :edit, :update, :destroy]

  # GET /animal_areas
  # GET /animal_areas.json
  def index
    @animal_areas = AnimalArea.all
  end

  # GET /animal_areas/areas.json
  def areas
    @animal_areas = AnimalArea.all
    @areas= []
    @animal_areas.each do |area|
      @areas << {
        data: {
          # Currently this is a circle, could be a marker, polygon, polyline, or cluster
          # Could contain things like colours, infoWindows (markers only), sizes, text, additional JSON etc. 
          lng: area.longitude,
          lat: area.latitude,
          radius: 200
        },
        options: {
          #For available options see:
          #https://github.com/apneadiving/Google-Maps-for-Rails/tree/master/vendor/assets/javascripts/gmaps/google/builders
          #(Warning, coffeescript)
        }
      }
    end
    render json: @areas
  end

  # GET /animal_areas/1
  # GET /animal_areas/1.json
  def show
  end

  # GET /animal_areas/new
  def new
    @animal_area = AnimalArea.new
  end

  # GET /animal_areas/1/edit
  def edit
  end

  # POST /animal_areas
  # POST /animal_areas.json
  def create
    @animal_area = AnimalArea.new(animal_area_params)

    respond_to do |format|
      if @animal_area.save
        format.html { redirect_to @animal_area, notice: 'Animal area was successfully created.' }
        format.json { render action: 'show', status: :created, location: @animal_area }
      else
        format.html { render action: 'new' }
        format.json { render json: @animal_area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animal_areas/1
  # PATCH/PUT /animal_areas/1.json
  def update
    respond_to do |format|
      if @animal_area.update(animal_area_params)
        format.html { redirect_to @animal_area, notice: 'Animal area was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @animal_area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animal_areas/1
  # DELETE /animal_areas/1.json
  def destroy
    @animal_area.destroy
    respond_to do |format|
      format.html { redirect_to animal_areas_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_animal_area
    @animal_area = AnimalArea.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def animal_area_params
    params.require(:animal_area).permit(:forward_sorting_area, :dogs, :cats, :latitude, :longitude)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/animal_areas_helper.rb
module AnimalAreasHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/animal_areas/_form.html.erb
<%= form_for(@animal_area) do |f| %>
  <% if @animal_area.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@animal_area.errors.count, "error") %> prohibited this animal_area from being saved:</h2>

      <ul>
      <% @animal_area.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :forward_sorting_area %><br>
    <%= f.text_field :forward_sorting_area %>
  </div>
  <div class="field">
    <%= f.label :dogs %><br>
    <%= f.number_field :dogs %>
  </div>
  <div class="field">
    <%= f.label :cats %><br>
    <%= f.number_field :cats %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/animal_areas/edit.html.erb
<h1>Editing animal_area</h1>

<%= render 'form' %>

<%= link_to 'Show', @animal_area %> |
<%= link_to 'Back', animal_areas_path %>

app/views/animal_areas/index.html.erb
<div style='width: 1200px;'>
  <div id="map" style='width: 1200px; height: 700px;'></div>
</div>

<h1>Listing animal_areas</h1>

<table>
  <thead>
    <tr>
      <th>Forward sorting area</th>
      <th>Dogs</th>
      <th>Cats</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @animal_areas.each do |animal_area| %>
      <tr>
        <td><%= animal_area.forward_sorting_area %></td>
        <td><%= animal_area.dogs %></td>
        <td><%= animal_area.cats %></td>
        <td><%= animal_area.latitude %></td>
        <td><%= animal_area.longitude %></td>
        <td><%= link_to 'Show', animal_area %></td>
        <td><%= link_to 'Edit', edit_animal_area_path(animal_area) %></td>
        <td><%= link_to 'Destroy', animal_area, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Animal area', new_animal_area_path %>

app/views/animal_areas/new.html.erb
<h1>New animal_area</h1>

<%= render 'form' %>

<%= link_to 'Back', animal_areas_path %>

app/views/animal_areas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Forward sorting area:</strong>
  <%= @animal_area.forward_sorting_area %>
</p>

<p>
  <strong>Dogs:</strong>
  <%= @animal_area.dogs %>
</p>

<p>
  <strong>Cats:</strong>
  <%= @animal_area.cats %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @animal_area.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @animal_area.longitude %>
</p>

<%= link_to 'Edit', edit_animal_area_path(@animal_area) %> |
<%= link_to 'Back', animal_areas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Catsanddogs</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

<%= yield %>

</body>
</html>